# FUNDING.yml

github: [your-github-username] # GitHub Sponsors (if applicable)
buy_me_a_coffee: https://buymeacoffee.com/shinhyesun
patreon: your-patreon-username # Patreon username
ko_fi: your-kofi-username # Ko-fi username
open_collective: your-opencollective-username # Open Collective username
liberapay: your-liberapay-username # Liberapay username
issuehunt: your-issuehunt-username # IssueHunt username
otechie: your-otechie-username # Otechie username
lfx_crowdfunding: your-lfx-crowdfunding-username # Linux Foundation crowdfunding
custom: ["https://your-custom-donation-url.com"] # Custom donation URL (optional)
